name: Tests
on: 
  pull_request:
    branches:
      - master
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run Tests
        run: yarn test:unit
