name: Tests
on:
  pull_request:
    branches:
      - master
env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - name: Run Tests
        run: yarn test:unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Run Tests
        run: yarn test:integration
